# -*- coding: utf-8 -*-
"""enco6a-tdd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gI3Imfl12NfmukGr3WuaiIBCy1G15rwR

# **Enunciado**

Implemente um calculador de desconto que receba o valor original de um produto
e aplique uma política de desconto, retornando o valor final.

As políticas possíveis
são:

*   Sem desconto — retorna o valor original.
*   Desconto percentual — aplica um percentual fixo (ex.: 10%).
*   Desconto por cupom — subtrai um valor fixo (ex.: R$ 20,00), nunca
resultando em valor negativo.

**Passos**:
1. **Vermelho (Red)**. Escreva os testes unitários para as três políticas de
desconto antes de implementar qualquer lógica. Os testes devem falhar neste
momento, pois isso é esperado e correto. Faça o commit com a mensagem
red: testes iniciais.
2. **Verde (Green)**. Implemente a solução mais simples possível para fazer todos
os testes passarem. Não se preocupe com elegância ou estrutura nesta
etapa, pois o objetivo é apenas ver os testes em verde. Faça o commit com a
mensagem green: implementação mínima.
3. **Refatorar (Refactor)**. Aplique o padrão de projeto selecionado para sua
aplicação. A interface pública e os testes não devem mudar; apenas a
estrutura interna. Verifique que todos os testes continuam passando e faça o
commit com a mensagem refactor: padrão Strategy aplicado.

# **Ciclo Vermelho**
"""

import unittest

class TestDiscountCalculator(unittest.TestCase):

  def setUp(self):
    self.calculator = DiscountCalculator()

  def test_no_discount(self):
    value = 100.0
    self.assertEqual(self.calculator.calculate_no_discount(value), 100.0)

  def test_percentage_discount(self):
    value = 100.0
    percentage = 0.10 # 10%
    self.assertEqual(self.calculator.calculate_percentage_discount(value, percentage), 90.0)

  def test_coupon_discount(self):
    value = 100.0
    coupon = 20.0
    self.assertEqual(self.calculator.calculate_coupon_discount(value, coupon), 80.0)

  def test_coupon_not_negative(self):
    value = 10.0
    coupon = 50.0
    self.assertEqual(self.calculator.calculate_coupon_discount(value, coupon), 0.0)

unittest.main(argv=['first-arg-is-ignored'], exit=False)

"""Aqui, observamos que a classe ainda não foi implementada. Por isso, nossos testes unitários ainda não funcionam. Implementaremos a classe DiscountCalculator de acordo com os testes, para que eles sejam aprovados.

# **Ciclo Verde**
"""

class DiscountCalculator:

    def calculate_no_discount(self, value):
      return value

    def calculate_percentage_discount(self, value, percentage):
      return value * (1 - percentage)

    def calculate_coupon_discount(self, value, coupon):
      return max(0, value - coupon) # Sem valores negativos

unittest.main(argv=['first-arg-is-ignored'], exit=False)

"""Observamos aqui que a nossa classe passou nos 4 testes, tendo um output igual ao esperado para cada caso. Agora, vamos para a parte de refatoração.

# **Refatoração**
Nesta etapa, dividimos a nossa calculadora em diferentes classes, seguindo o padrão de projeto Strategy.

> *Strategy is a behavioral design pattern that lets you define a family of algorithms, put each of them into a separate class, and make their objects interchangeable.*

Referência: https://refactoring.guru/design-patterns/strategy
"""

from abc import ABC, abstractmethod

# Interface Strategy
class DiscountStrategy(ABC):
    @abstractmethod
    def calculate(self, value):
        pass

# Estratégias Concretas
class NoDiscount(DiscountStrategy):
    def calculate(self, value):
        return value

class PercentageDiscount(DiscountStrategy):
    def __init__(self, percentage):
        self.percentage = percentage

    def calculate(self, value):
        return value * (1 - self.percentage)

class CouponDiscount(DiscountStrategy):
    def __init__(self, coupon):
        self.coupon = coupon

    def calculate(self, value):
        return max(0, value - self.coupon)

# Contexto (Refatorado)
class DiscountCalculator:
    def calculate_no_discount(self, value):
        strategy = NoDiscount()
        return strategy.calculate(value)

    def calculate_percentage_discount(self, value, percentage):
        strategy = PercentageDiscount(percentage)
        return strategy.calculate(value)

    def calculate_coupon_discount(self, value, coupon):
        strategy = CouponDiscount(coupon)
        return strategy.calculate(value)

# Execução dos testes para validar a refatoração
print("Validando refatoração com os testes existentes:")
unittest.main(argv=['first-arg-is-ignored'], exit=False)

"""Por fim, observamos que todos os testes continuam sendo aprovados após a refatoração, validando a nossa estratégia de desenvolver utilizando TDD. Esta abordagem faz com que refatorações não quebrem a lógica preexistente do código."""